export type KeyStroke = {
  code: string;
  metaKey: boolean;
  ctrlKey: boolean;
  altKey: boolean;
  shiftKey: boolean;
};
const labels: Record<string, string> = {
  CommandOrControl: '⌘',
  Command: '⌘',
  Meta: '⌘',
  Super: '⌘',
  Control: '⌃',
  Ctrl: '⌃',
  Alt: '⌥',
  Option: '⌥',
  Shift: '⇧',
  Space: 'Space',
  Enter: '↩',
  Tab: '⇥',
  Backspace: '⌫',
  Delete: '⌦',
  ArrowUp: '↑',
  ArrowDown: '↓',
  ArrowLeft: '←',
  ArrowRight: '→',
  Minus: '−',
  Equal: '=',
  BracketLeft: '[',
  BracketRight: ']',
  Backslash: '\\',
  Semicolon: ';',
  Quote: '′',
  Backquote: '`',
  Comma: ',',
  Period: '.',
  Slash: '/',
};
export const shortcutKeys = (shortcut: string) =>
  shortcut
    .split('+')
    .filter(Boolean)
    .map((s) => labels[s] || s.replace(/^Key|^Digit/, ''));
export function recordStroke(e: KeyStroke) {
  const modifiers = [
    e.ctrlKey && 'Control',
    e.altKey && 'Alt',
    e.shiftKey && 'Shift',
    e.metaKey && 'Command',
  ].filter(Boolean) as string[];
  const modifierOnly = /^(Meta|Control|Alt|Shift)/.test(e.code) || !e.code;
  const supported =
    /^(Key[A-Z]|Digit[0-9]|F([1-9]|1[0-9]|20))$/.test(e.code) ||
    [
      'Space',
      'Enter',
      'Tab',
      'Backspace',
      'Delete',
      'ArrowUp',
      'ArrowDown',
      'ArrowLeft',
      'ArrowRight',
      'Home',
      'End',
      'PageUp',
      'PageDown',
      'Minus',
      'Equal',
      'BracketLeft',
      'BracketRight',
      'Backslash',
      'Semicolon',
      'Quote',
      'Backquote',
      'Comma',
      'Period',
      'Slash',
    ].includes(e.code);
  const value = [...modifiers, ...(!modifierOnly && supported ? [e.code] : [])].join('+');
  if (modifierOnly) return { value, complete: false, error: '' };
  if (!supported) return { value, complete: false, error: 'Try another key.' };
  if (!e.metaKey && !e.ctrlKey && !e.altKey)
    return { value, complete: false, error: 'Include ⌘, ⌥, or ⌃.' };
  return { value, complete: true, error: '' };
}
const macCodes: Record<number, string> = {
  0: 'KeyA',
  1: 'KeyS',
  2: 'KeyD',
  3: 'KeyF',
  4: 'KeyH',
  5: 'KeyG',
  6: 'KeyZ',
  7: 'KeyX',
  8: 'KeyC',
  9: 'KeyV',
  11: 'KeyB',
  12: 'KeyQ',
  13: 'KeyW',
  14: 'KeyE',
  15: 'KeyR',
  16: 'KeyY',
  17: 'KeyT',
  18: 'Digit1',
  19: 'Digit2',
  20: 'Digit3',
  21: 'Digit4',
  22: 'Digit6',
  23: 'Digit5',
  24: 'Equal',
  25: 'Digit9',
  26: 'Digit7',
  27: 'Minus',
  28: 'Digit8',
  29: 'Digit0',
  30: 'BracketRight',
  31: 'KeyO',
  32: 'KeyU',
  33: 'BracketLeft',
  34: 'KeyI',
  35: 'KeyP',
  36: 'Enter',
  37: 'KeyL',
  38: 'KeyJ',
  39: 'Quote',
  40: 'KeyK',
  41: 'Semicolon',
  42: 'Backslash',
  43: 'Comma',
  44: 'Slash',
  45: 'KeyN',
  46: 'KeyM',
  47: 'Period',
  48: 'Tab',
  49: 'Space',
  50: 'Backquote',
  51: 'Backspace',
  53: 'Escape',
  54: 'MetaRight',
  55: 'MetaLeft',
  56: 'ShiftLeft',
  58: 'AltLeft',
  59: 'ControlLeft',
  60: 'ShiftRight',
  61: 'AltRight',
  62: 'ControlRight',
  64: 'F17',
  79: 'F18',
  80: 'F19',
  90: 'F20',
  96: 'F5',
  97: 'F6',
  98: 'F7',
  99: 'F3',
  100: 'F8',
  101: 'F9',
  103: 'F11',
  105: 'F13',
  106: 'F16',
  107: 'F14',
  109: 'F10',
  111: 'F12',
  113: 'F15',
  115: 'Home',
  116: 'PageUp',
  117: 'Delete',
  118: 'F4',
  119: 'End',
  120: 'F2',
  121: 'PageDown',
  122: 'F1',
  123: 'ArrowLeft',
  124: 'ArrowRight',
  125: 'ArrowDown',
  126: 'ArrowUp',
};
export function nativeStroke(e: { code: number; flags: number; down: boolean }): KeyStroke {
  return {
    code: e.down ? macCodes[e.code] || 'Unsupported' : '',
    ctrlKey: !!(e.flags & 1),
    altKey: !!(e.flags & 2),
    shiftKey: !!(e.flags & 4),
    metaKey: !!(e.flags & 8),
  };
}
